[package]
name = "tacy-and-terry-destroy-the-world"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
edition = "2018"

[dependencies]
reqwest = "*"

[[bin]]
name = "destiny-char"
path = "destiny-char.rs"
