[package]
name = "tacy-and-terry-destroy-the-world"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
edition = "2018"

[dependencies]
reqwest = "*"
json = "*"  
serde = "*"
serde_json = "*"
rustc-serialize = "*"

[[bin]]
name = "main"
path = "inventory/src/main.rs"
